# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7be1bfa55e8d8fb2398de1629cc356057f50c0aa9b463296b027a16dea7d58bd18c5371650d00b30f016d2a4a97c7902986695e107f93c3ad865943ddac6da3

test:
  secret_key_base: 3891c5eb32f5a846167d5e170bc3b6b1ba92bdd666c874db8d244981aadb3a7a9b533d2438ec53418ab77004e597322b440df6e27a1995b55fa926c5a4d29940

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
